language: python
dist: xenial

python: 3.7.3

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r dev-requirements.txt

script:
  - pip install -e .
  - black --check crab/ setup.py
  - ./scripts/build_binary.sh
